schema_version: 1

context:
  version: "6.2.6"

package:
  name: cachebox
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/c/cachebox/cachebox-${{ version }}.tar.gz
  sha256: ba2c2afe8f55ba5006327dd5e444d26a4bc49084653416bbab7d7f4989924395

build:
  number: 0
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - crossenv
        - maturin >=1.8,<2
    - ${{ compiler("c") }}
    - ${{ compiler("rust") }}
    - ${{ stdlib("c") }}
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=1.8,<2.0
    - pip
  run:
    - python

tests:
  - python:
      imports:
        - cachebox
      pip_check: true

about:
  summary: The fastest caching Python library written in Rust
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  homepage: https://github.com/awolverp/cachebox
  repository: https://github.com/awolverp/cachebox

extra:
  recipe-maintainers:
    - synapticarbors
